# Generated by Django 4.0.3 on 2022-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('desc', models.TextField(verbose_name='desc')),
                ('ort_needed', models.PositiveIntegerField(default=150, verbose_name='needed ort')),
                ('fee', models.PositiveIntegerField(default=700, verbose_name='fee')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
